learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("learning_logs.urls")),
    path("users/", include("users.urls")),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path

from . import views


app_name = "learning_logs"
urlpatterns = [
    path("", views.index, name="index"),
    # Page that shows all available topics
    path("topics/", views.topics, name="topics"),
    # Detailed page for a single topic
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    # Page for adding new topic
    path("new_topic/", views.new_topic, name="new_topic"),
    # Page for adding new entry
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    # Page for editing an entry
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

users/urls.py
"""Defines URL patterns for users."""
from django.urls import path, include

from . import views


app_name = "users"
urlpatterns = [
    # Include default auth urls.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."

        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def check_topic_owner(topic, request):
    """Raises 404 Error if user does not have access the wrong page."""
    if topic.owner != request.user:
        raise Http404


def index(request):
    """The home page for Learning Log."""
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """Show all topics from a specific user."""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    # topics = Topic.objects.order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    # The minus sign in front of date_added sorts the result in reverse order.
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != "POST":
        # No data submitted, create a blank form
        form = TopicForm()
    else:
        # POST data submitted; create a blank form
        form = TopicForm(data=request.POST)

        if form.is_valid():
            # Add the current topic for the current logged in user.
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    # Display a blank or invalid form
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    if request.method != "POST":
        # No data submitted; create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    # Display a blank form or invalid form
    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != "POST":
        # Initial request; pre-fill form with current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != "POST":
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # POST data submitted; process data
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            # Log in the user and then redirect to home page.
            login(request, new_user)
            return redirect("learning_logs:index")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Learning Logs</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<body class="px-3">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <strong class="navbar-item is-size-4">Learning Log</strong>

      <button role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </button>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <ul class="navbar-start">
        <li class="navbar-item">
          <a href="{% url 'learning_logs:index' %}">Home</a>
        </li>
        <li class="navbar-item">
          <a href="{% url 'learning_logs:topics' %}">Topics</a>
        </li>
      </ul>

      <ul class="navbar-end">
        {% if user.is_authenticated %}
          <li class="navbar-item">{{ user.username|title }}</li>
          <li class="navbar-item">
            <a href="{% url 'users:logout' %}" class="button is-danger">Logout</a>
          </li>
        {% else %}
          <li class="navbar-item">
            <a href="{% url 'users:register' %}" class="button is-primary">Sign up</a>
          </li>
          <li class="navbar-item">
            <a href="{% url 'users:login' %}" class="button is-light">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main class="container p-3">
    {% block content %}{% endblock content %}
  </main>

<script>
  const menuToggle = document.querySelector(".navbar-burger");
  const navbarMenu = document.querySelector(".navbar-menu");
  menuToggle.addEventListener("click", () => {
    menuToggle.classList.toggle("is-active");
    navbarMenu.classList.toggle("is-active");
  });
</script>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p class="mb-3"><a href="{% url 'learning_logs:topic' topic.id %}">Back to {{ topic }}</a></p>

  <p class="mb-1">Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-success" name="submit">Save changes</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <section class="container p-3">
    <div class="hero">
      <h1 class="title">Track Your Learning</h1>

      <p class="">Make your own Learning Log, and keep a list of all the topics you're learning about.
        <br>
        Whenever you learn something new about a topic, make an entry summarizing what you've learned.
      </p>
    </div>
    <a class="button is-info mt-4" href="{% url 'users:register' %}">Register >>></a>
  </section>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p class="mb-3"><a href="{% url 'learning_logs:topic' topic.id %}">Back to {{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-success" name="submit">Add entry</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2 class="subtitle">Add a new topic:</h2>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="control mt-5">
      <button class="button is-success" name="submit">Add topic</button>
    </div>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2 class="subtitle"><b>Topic: {{ topic }}</b></h2>

  <p class="is-size-5 mb-3">Entries:</p>

  <p class="mb-4"><a class="button is-success"
    href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a></p>

  <article class="ml-4">
    {% for entry in entries %}
      <section class="mb-6">
        <p class="is-italic"><small>{{ entry.date_added|date:'M d, Y P' }}</small></p>
        <p>{{ entry.text|linebreaks }}</p>

        <p><a class="button is-link is-light is-small mt-2"
          href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></p>
      </section>
    {% empty %}
      <div>There are no entries for this topic yet.</div>
    {% endfor %}
  </article>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h1 class="title is-size-4 mt-3">Topics</h1>

  <ul>
    {% for topic in topics %}
      <li class="mb-3">
        * <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a class="button is-light" href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}